#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $Eagle_repo == "Eagle" ]]
    then 
        echo "YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDB0cGJtZGhZMmhsTDBWaFoyeGxMMkZ5WTJocGRtVXZiV0ZwYmk1NmFYQT0=" | base64 -d
    elif [[ $Eagle_repo == "Eagle" ]]
    then
        echo "YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDB0cGJtZGhZMmhsTDBWaFoyeGxMMkZ5WTJocGRtVXZiV0ZwYmk1NmFYQT0=" | base64 -d
    elif [[ $Eagle_repo =~ $regex ]]
    then
        if [[ $Eagle_repo_branch ]]
        then
            echo "${Eagle_repo}/archive/${Eagle_repo_branch}.zip"
        else
            echo "${Eagle_repo}/archive/main.zip"
        fi
    else
        echo "YUhSMGNITTZMeTluYVhSb2RXSXVZMjl0TDB0cGJtZGhZMmhsTDBWaFoyeGxMMkZ5WTJocGRtVXZiV0ZwYmk1NmFYQT0=" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="Eagle.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    EAGLESPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $EAGLESPATH
    echo " i love you "
    sleep 5
    echo "  • Starting Userbot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m Eagle
}

start_bot
