#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "Eagle-Ubot" ]]
    then 
        echo "aHR0cHM6Ly9naXRodWIuY29tL0tpbmdhY2hlL0VhZ2xlLVVib3QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO == "Eagle-Ubot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0tpbmdhY2hlL0VhZ2xlLVVib3QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO_BRANCH}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO_BRANCH}/archive/main.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0tpbmdhY2hlL0VhZ2xlLVVib3QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="main.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    EAGLESPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $EAGLESPATH
    echo " i love you "
    sleep 5
    echo "  • Starting Userbot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m eagle
}

start_bot
